### ISSUE TITLE
后台持续下载

### ISSUE THREAD

**Issue by lengyijun** [allenliu123/douyin#6]
能否支持这个功能:
放在后台运行, 每天检测一次, 有新的就下载?

**Comment by allenliu123** [comment]
你是要放到服务器上去跑吗？用 crontab 呗

**Comment by lengyijun** [comment]
请问一下现在有避免重复下载的机制吗?

**Comment by allenliu123** [comment]
目前还没有，我加下这个功能，预计本周日前能搞完

**Comment by allenliu123** [comment]
已增加避免重复下载的功能，可以重新拉下代码试下

**Comment by lengyijun** [comment]
简单试了一下, 可以用
准备设一个 crontab 长期运行
